apiVersion: v1
kind: Service
metadata:
    name: frontend-svc
    namespace: dev
spec:
    type: LoadBalancer
    selector:
        app: frontend
    ports:
    - name:  frontendport
      port:  80
      targetPort: http
      protocol: TCP
